# To skip files from linter check add file path here

run:
  timeout: 5m
  concurrency: 4
  allow-parallel-runners: false
  modules-download-mode: mod
  tests: false
  go: "1.23"
severity:
  default-severity: error
linters:
  disable-all: true
  fast: false
  enable:
    - gosimple
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - bidichk
    - cyclop
    - decorder
    - dogsled
    - dupl
    - errchkjson
    - errname
    - errorlint
    - forcetypeassert
    - funlen
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - gofmt
    - goimports
    - mnd
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - maintidx
    - makezero
    - misspell
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - nlreturn
    - nolintlint
    - nonamedreturns
    - nosprintfhostport
    - paralleltest
    - prealloc
    - predeclared
    - revive
    - stylecheck
    - tagliatelle
    - tenv
    - testpackage
    - thelper
    - tparallel
    - unconvert
    - unparam
    - varnamelen
    - tagliatelle

linters-settings:
  lll:
    line-length: 120
  funlen:
    lines: 75
    statements: 60
  govet:
    shadow: true
  goconst:
    min-len: 4
    min-occurrences: 3
    ignore-tests: true
  whitespace:
    multi-func: false
    multi-if: false
  gocyclo:
    min-complexity: 50
  cyclop:
    skip-tests: true
    max-complexity: 20
  dogsled:
    max-blank-identifiers: 2
  errorlint:
    errorf: true
  godot:
    period: true
    capital: true
  nestif:
    min-complexity: 6
  gci:
    skip-generated: true
  gocognit:
    min-complexity: 50
  varnamelen:
    min-name-length: 2
    check-return: true
  dupl:
    threshold: 550
  godox:
    keywords:
      - WARN
  revive:
    severity: warning
    rules:
      - name: atomic
      - name: duplicated-imports
  tagliatelle:
    case:
      rules:
        json: snake
  staticcheck:
    checks:
      - "all"
      - "-SA1019"
  gosec:
    excludes:
      - G601
      - G113
      - G115

issues:
  max-issues-per-linter: 50
  max-same-issues: 3
  exclude-dirs:
    - mocks
    - examples
    - design
# output configuration options
output:
  # Default: colored-line-number
  formats: colored-line-number
  # Print lines of code with issue.
  # Default: true
  print-issued-lines: false
  # Print linter name in the end of issue text.
  # Default: true
  print-linter-name: true
  # Make issues output unique by line.
  # Default: true
  uniq-by-line: false
  # Add a prefix to the output file references.
  # Default is no prefix.
  path-prefix: ""
  # Sort results by: filepath, line and column.
  sort-results: false